apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ybes
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ybes
    app.kubernetes.io/part-of: test-app-uwgp
  name: test-component-ybes
  namespace: build-e2e-hraj-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-ybes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-ybes
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:1c48e721cba55bde0fd8ad4c95bac5b4308f2db8de1f5cf5a06b65f8c2030c2c
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
