apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ybes
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ybes
    app.kubernetes.io/part-of: test-app-uwgp
  name: test-component-ybes
  namespace: build-e2e-hraj-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-ybes
status:
  loadBalancer: {}
